namespace Car_Rental
{
    partial class frm_Add_Car
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_Add_Car));
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.btnClear = new System.Windows.Forms.Button();
            this.btnSaveCar = new System.Windows.Forms.Button();
            this.btnBackToMenu = new System.Windows.Forms.Button();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtMake = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.txtCarModel = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.txtVin = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.cbYear = new System.Windows.Forms.ComboBox();
            this.cbColor = new System.Windows.Forms.ComboBox();
            this.cbTransmission = new System.Windows.Forms.ComboBox();
            this.label9 = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(1398, 792);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(102, 37);
            this.label2.TabIndex = 11;
            this.label2.Text = "label2";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 18F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Underline))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(599, 350);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(305, 82);
            this.label3.TabIndex = 10;
            this.label3.Text = "Add Car";
            // 
            // btnClear
            // 
            this.btnClear.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btnClear.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnClear.ForeColor = System.Drawing.Color.Red;
            this.btnClear.Location = new System.Drawing.Point(1049, 818);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new System.Drawing.Size(385, 156);
            this.btnClear.TabIndex = 9;
            this.btnClear.Text = "Clear";
            this.btnClear.UseVisualStyleBackColor = true;
            // 
            // btnSaveCar
            // 
            this.btnSaveCar.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btnSaveCar.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSaveCar.ForeColor = System.Drawing.Color.Red;
            this.btnSaveCar.Location = new System.Drawing.Point(584, 818);
            this.btnSaveCar.Name = "btnSaveCar";
            this.btnSaveCar.Size = new System.Drawing.Size(385, 156);
            this.btnSaveCar.TabIndex = 8;
            this.btnSaveCar.Text = "Save";
            this.btnSaveCar.UseVisualStyleBackColor = true;
            this.btnSaveCar.Click += new System.EventHandler(this.btnSaveCar_Click);
            // 
            // btnBackToMenu
            // 
            this.btnBackToMenu.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.btnBackToMenu.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBackToMenu.ForeColor = System.Drawing.Color.Red;
            this.btnBackToMenu.Location = new System.Drawing.Point(121, 818);
            this.btnBackToMenu.Name = "btnBackToMenu";
            this.btnBackToMenu.Size = new System.Drawing.Size(385, 156);
            this.btnBackToMenu.TabIndex = 7;
            this.btnBackToMenu.Text = "<- Back to Menu";
            this.btnBackToMenu.UseVisualStyleBackColor = true;
            this.btnBackToMenu.Click += new System.EventHandler(this.btnBackToMenu_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(462, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(593, 281);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 6;
            this.pictureBox1.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(104, 514);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(98, 37);
            this.label1.TabIndex = 12;
            this.label1.Text = "Make";
            // 
            // txtMake
            // 
            this.txtMake.AutoCompleteCustomSource.AddRange(new string[] {
            "AAD",
            "Abadal",
            "Abarth",
            "ABC",
            "Aberdonia",
            "ABT Sportsline",
            "Bajaj",
            "AC Cars",
            "AC Propulsion",
            "Acadian",
            "Acura",
            "Adam Motor Company, Ltd.",
            "Adams",
            "ADK",
            "Adler",
            "Aero",
            "Aeromobil",
            "Agrale",
            "AIL",
            "Aiways",
            "Aixam-Mega",
            "Ajax",
            "AJS",
            "Al Araba Company",
            "Alatac",
            "Albion",
            "Ales",
            "Alesbury",
            "Alfa Romeo Automobiles",
            "Alfgang",
            "Allard",
            "Alldays",
            "Alma",
            "Almac",
            "ALP",
            "Alpha Sports",
            "Alpine",
            "Alpina",
            "Alta",
            "Alta",
            "Alteliers Germain",
            "Alternative Cars Limited",
            "Alvis",
            "AM General",
            "Ambassador",
            "AMC",
            "AMCE",
            "American",
            "American Motors (AMC)",
            "American Underslung",
            "AMG",
            "Amherst",
            "Amilcar",
            "Amphicar",
            "Amuza",
            "Anadol",
            "Anasagasti",
            "Andino",
            "Andre",
            "Ansaldo",
            "Anteros Coachworks",
            "Antoine",
            "Anziel Nova",
            "Apal",
            "Apollo",
            "Apperson",
            "AR aka ARCO",
            "Arab",
            "Arab American Vehicles",
            "Arash",
            "Arcfox",
            "Argyll",
            "Ariel",
            "Arista",
            "Armstrong Siddeley",
            "Arnolt",
            "ARO",
            "Arola SARL",
            "Arrinera",
            "Arrival",
            "Arrol-Johnston",
            "Artega",
            "Artega Automobil GmbH",
            "ASA",
            "Asahi",
            "Ascari Cars Ltd.",
            "ASL",
            "Aspa",
            "Aspark",
            "Aspid",
            "Aspidis",
            "Aster",
            "Aston Martin",
            "Astra",
            "Asuna",
            "Atalanta",
            "Aton Impulse",
            "ATS",
            "Attica",
            "Auburn",
            "Audi",
            "Aurica Motors",
            "Austin",
            "Australian Motor Industries",
            "Australian Six",
            "Authi",
            "Autobacs",
            "Autobianchi",
            "Autobleu",
            "Autocars Co. Ltd.",
            "Autokinitoviomihania Ellados",
            "Automeccanica",
            "Auto-Union",
            "Autovia",
            "Auverland",
            "Avanti",
            "Avia",
            "AvtoVAZ",
            "AvtoZAZ",
            "AWZ",
            "Axon",
            "AZLK",
            "Car brands that start with B",
            "Car brands that start with B",
            "",
            "B Engineering",
            "B+B",
            "BAC",
            "BAIC Group",
            "Balaton",
            "Ballot",
            "Bandini Automobili",
            "Barkas",
            "Basil Green Motors",
            "Batten",
            "Bavarian Auto Group",
            "BAW",
            "Beattie",
            "BeiBen",
            "Beiqi",
            "Belga Rise",
            "Belkommunmash",
            "Belsize",
            "Bentley",
            "Berkeley",
            "Berliet",
            "Bernardini",
            "Bertone",
            "Bestune",
            "BharatBenz",
            "Biotechnia Ellinikon Trikyklon",
            "Birchfield Motor Company",
            "Birkin",
            "Birrana",
            "Bitter",
            "Bizzarrini",
            "Bjering",
            "BMW",
            "BMW M",
            "Bollee",
            "Bollore",
            "Bolwell",
            "Bond",
            "Borgward",
            "Bosmal",
            "Bowler",
            "Bourassa",
            "Brabus",
            "Brammo",
            "Brasinca",
            "Brems",
            "Brennabor-Werke",
            "Brewster",
            "Bricklin SV-1",
            "Briggs Automotive Company (BAC)",
            "Brilliance Auto Group",
            "Brisco",
            "Bristol",
            "British Salmson",
            "Brock Motors",
            "Brooke",
            "Brooks Steam Motors",
            "Brough Superior",
            "Brush",
            "Brutsch",
            "BSA",
            "Bucciali",
            "Buckle Motors",
            "Buckler",
            "Buddy",
            "Bufori",
            "Bugatti",
            "Buick",
            "Bukh & Gry",
            "Bulant",
            "Bulgaralpine",
            "Bullet",
            "Burton",
            "BUS",
            "Büssing",
            "Byton",
            "BXR",
            "BYD",
            "Car brands that start with C",
            "Car brands that start with C",
            "",
            "Cadillac",
            "Calthorpe",
            "Cambli International Thunder 1",
            "Campagna Corporation",
            "Canadian Motor",
            "Canoo",
            "Caparo",
            "Carlsson",
            "Carroll Shelby",
            "Casalini",
            "Case",
            "Castagna",
            "Caterham",
            "Centenari",
            "Central Motor Co., Ltd",
            "CG",
            "Chadwick",
            "Champion",
            "Chandler",
            "Chang’an Automobile Group",
            "Changfeng",
            "Changhe",
            "Chariot Motors",
            "Checker",
            "Cheetah Racing",
            "Chenard-Walcker",
            "Chery Automobile Co",
            "Chevrolet",
            "Chevron Engineering Specialties",
            "Chinkara Motors",
            "Chiribiri",
            "Chrysler",
            "Cisitalia",
            "Citroen",
            "CityEl",
            "Cizeta",
            "Clan",
            "Claveau",
            "Clinton",
            "CMC",
            "Colonial Motors Ltd",
            "Comet",
            "Commuter",
            "Compagnie Nationale Excelsior",
            "Connaught",
            "Continental",
            "Cooper",
            "Cord",
            "Corre La Licorne",
            "Corvette",
            "Costin",
            "Cottin-Desgouttes",
            "Covini Engineering",
            "Crossley",
            "CSC",
            "Csonka",
            "CT&T United",
            "Cunningham",
            "Cupra",
            "Custoca",
            "Car brands that start with D",
            "Car brands that start with D",
            "",
            "Dacia",
            "Dacon",
            "Dadi Auto",
            "Daewoo Motors",
            "DAF",
            "Dagmar",
            "Daihatsu",
            "Daimler",
            "Daimler",
            "Dakar",
            "Darracq",
            "Darracq Lago",
            "Dartz Motorz Company",
            "Datsun",
            "Dauer",
            "David Brown Automotive",
            "Davis",
            "Davrian",
            "Daytona Motors",
            "Dayun",
            "DB",
            "De Dietrich",
            "De Dion Bouton",
            "De Lorean",
            "De Soto",
            "De Tomaso",
            "De Wandre",
            "Deep Sanderson",
            "DeLaChapelle",
            "Delage",
            "Delahaye",
            "Delecroix",
            "Dellow",
            "Denzel",
            "Derby",
            "Derways",
            "Detroit Electric",
            "Devaux Pty Ltd",
            "Devon Motorworks",
            "Devrim",
            "Diana",
            "Diar",
            "Diardi",
            "Diatto",
            "DIM Motor Company",
            "Dinap",
            "Diva",
            "Dixi",
            "DKW",
            "DKW-Vemag",
            "DMC",
            "Dodge",
            "Dodge Viper",
            "Dome",
            "Dominion",
            "Dongfeng Motor Corporation",
            "Donkervoort Automobielen BV",
            "Dort",
            "DR Motor Company",
            "Drako",
            "Dragon",
            "DRB",
            "DS",
            "Du Pont",
            "Duesen Bayern",
            "Duesenberg",
            "Dufaux",
            "Duplex",
            "Durant",
            "Durkopp",
            "Duryea",
            "Dutton",
            "Dynasty Electric",
            "Car brands that start with E",
            "Car brands that start with E",
            "",
            "Eagle",
            "Ecosse",
            "Edfor",
            "EDAG",
            "Edran",
            "Edsel",
            "EGA",
            "Egy-Tech Engineering",
            "Eicher",
            "Elcar",
            "Elcat Automotive",
            "Elemental",
            "Elfin",
            "Elva",
            "ELVO",
            "EMF",
            "Emme",
            "Emporiki Autokiniton",
            "Engesa",
            "Englon",
            "Enterra Vipre",
            "Enzmann 506",
            "ErAZ",
            "ERF Trucks",
            "Eshelman",
            "Espenlaub",
            "Esther",
            "Eterniti Motors",
            "Etox",
            "Eurostar Automobilwerk GesmbH & Co. KG",
            "Everus (Li Nian)",
            "Exagon Engineering",
            "Excel Motors Limited",
            "Exeed",
            "Exelsior",
            "Car brands that start with F",
            "Car brands that start with F",
            "",
            "Fabrica Nacional de Motores",
            "Fabrique Nationale",
            "Facel Vega",
            "Fafnir",
            "Fageol",
            "Fairthorpe",
            "Falcon Motorsports",
            "Faraday Future",
            "Faralli and Mazzanti",
            "Farbio",
            "Farboud",
            "FAW Group Corporation",
            "FAW Tianjin",
            "FBS",
            "Fejes",
            "Felber Autoroller",
            "Ferrari",
            "Fiat",
            "Finlandia",
            "Fioravanti",
            "Firestone-Columbus",
            "Fisker Automotive, Inc",
            "Fitch",
            "Fleetwood-Knight",
            "Flint",
            "Foden Trucks",
            "Force Motors",
            "Ford",
            "Ford Performance Vehicles (FPV)",
            "Fornasari",
            "Foton Motor",
            "Franklin",
            "Fraser Clubman",
            "Freightliner",
            "Frisky",
            "FSC Lublin",
            "FSO",
            "Fujian Motors",
            "Fuldamobil",
            "FYK",
            "Car brands that start with G",
            "Car brands that start with G",
            "",
            "GAC Changfeng Motor",
            "GAC Group",
            "GAIG",
            "Gardner",
            "Gareau",
            "Gaselle",
            "GAZor",
            "Geely",
            "Geijer & Co",
            "GEM",
            "Genesis",
            "Geo",
            "Geometry",
            "Ghabbour Group",
            "Ghia",
            "Giad Auto",
            "Gilbern",
            "Gillet",
            "Ginetta",
            "Giocattolo Motori",
            "Giottiline",
            "GKD",
            "GKN",
            "Glas",
            "GM",
            "GMC",
            "GN",
            "Gnome",
            "Goggomobil",
            "Golden Dragon",
            "Goliath",
            "Gonow",
            "Gordon-Keeble",
            "Graf & Stift",
            "Graham",
            "Grant",
            "Gray",
            "Gray-Dort Motors",
            "Great Wall Motors Company Limited",
            "Gregoire",
            "Grieve",
            "Griffith",
            "Grinnall",
            "Grofri",
            "Grupo Industrial Ramirez",
            "GSM",
            "GTA Motor",
            "Gumpert",
            "Gurgel Motores",
            "Gutbrod",
            "Guy",
            "Car brands that start with H",
            "Car brands that start with H",
            "",
            "Habib Motors",
            "Hafei",
            "HAIMA",
            "HAL",
            "Hammer",
            "Hanomag",
            "Hansa",
            "Hartge",
            "Haval",
            "Hawtai",
            "Healey",
            "Heinkel",
            "Heinkel Kabine",
            "Heng",
            "Hennessey",
            "Heron",
            "Hertz",
            "Heuliez",
            "Higer",
            "Highland",
            "Hillman",
            "Hindustan Motors",
            "Hino",
            "HiPhi",
            "Hispano Argentina",
            "Hispano-Suiza",
            "Hofstetter Turbo",
            "Holden",
            "Holland Car PLC",
            "Honda",
            "Hongqi",
            "Hope Motor Company",
            "Horch",
            "Hotchkiss",
            "HRG",
            "HSV",
            "HTT Plethore",
            "Hyundai",
            "Huali",
            "Hualing Xingma (CAMC)",
            "Huayang",
            "Hudson",
            "Humber",
            "Hupmobile",
            "Hurtan Desarrollos S.L.",
            "Hurtu",
            "Car brands that start with I",
            "Car brands that start with I",
            "",
            "IAME",
            "IC Bus",
            "IDA-Opel",
            "IFR Aspid",
            "IHI Corporation",
            "IKA",
            "IKCO",
            "Ilinga",
            "Imperia Automobiles",
            "Imperial",
            "Infiniti",
            "Innocenti",
            "Intermeccanica",
            "International Harvester",
            "International Trucks",
            "Invicta",
            "Iota",
            "IPML",
            "Irizar",
            "Irmscher",
            "Isatis",
            "Isdera",
            "Iso",
            "Isotta-Fraschini",
            "Isuzu",
            "Itala",
            "Italdesign",
            "Iveco",
            "IZh",
            "Car brands that start with J",
            "Car brands that start with J",
            "",
            "JAC Motors",
            "Jaguar",
            "JAWA",
            "JBA Motors",
            "Jeecy-Vea",
            "Jeep",
            "Jensen Motors",
            "Jetta",
            "Jiangling Motors Corporation",
            "Jiotto",
            "JMC",
            "Jordan",
            "JOSS",
            "Josse",
            "Jowett",
            "JPX do Brasil Ltda.",
            "Juwel",
            "Car brands that start with K",
            "Car brands that start with K",
            "",
            "Kaditcha",
            "Kaipan",
            "Kaiser",
            "Kantanka",
            "Karma",
            "Karmann",
            "Karosa",
            "Keating Supercars",
            "Keinath",
            "Keller",
            "Kenworth Truck",
            "Kewet",
            "Kia Motors Corporation",
            "Kieft",
            "King Long",
            "Kish Khodro",
            "Kissel",
            "Kleinschnittger",
            "Knox",
            "Koenig",
            "Koenigsegg",
            "Korvensuu",
            "Car brands that start with L",
            "Car brands that start with L",
            "",
            "La Buire",
            "La Fayette",
            "La Salle",
            "Lada",
            "Lagonda",
            "Lamborghini",
            "Lammas-Graham",
            "Lanchester",
            "Lancia",
            "Land Rover",
            "LandFighter",
            "Laurin and Klement",
            "LDS",
            "Le Zebre",
            "Leader",
            "Lea-Francis",
            "Leblanc",
            "Ledl",
            "Leidart",
            "Leon Bollee",
            "LeRoy",
            "Lexington",
            "Lexus",
            "Leyland",
            "Li Auto",
            "LIAZ",
            "Libelle",
            "Libyan Rocket",
            "Licorne",
            "Lida Buses Neman",
            "Lifan",
            "Lifan Ethiopia",
            "Lightning",
            "Ligier",
            "Lincoln",
            "Lister",
            "Litex Motors",
            "Lloyd",
            "LMX",
            "Lobini",
            "Locomobile",
            "Lola",
            "Lombard",
            "London EV Company (LEVC)",
            "London Motors",
            "Lordstown",
            "Lorraine",
            "Lorraine Dietrich",
            "Lotec",
            "Lotus",
            "Lozier",
            "LTI",
            "LuAZ",
            "Lucalia Clubman",
            "Lucid",
            "Lutzmann",
            "Luxgen Motor Co., Ltd.",
            "Lynk & Co",
            "Car brands that start with M",
            "Car brands that start with M",
            "",
            "Mack Trucks",
            "Magna Steyr",
            "Magna Steyr AG & Co KG",
            "Mahindra & Mahindra",
            "Mahindra Reva Electric Vehicles",
            "Maico",
            "MAN",
            "Manic GT",
            "Mansory",
            "Marauder",
            "Marcos Engineering",
            "Marendaz",
            "Markranstadter Automobilfabrik",
            "Marlei",
            "Marmon",
            "Marlin",
            "Martin",
            "Martini",
            "Marussia Motors",
            "Maruti Suzuki India",
            "Maserati",
            "Mastretta",
            "Matra",
            "Matra Bonnet",
            "Matra-Simca",
            "Matra-Talbot",
            "Maudslay",
            "MAVA",
            "Maxwell",
            "Maxus",
            "Maybach",
            "Mazda",
            "Mazzanti",
            "MCC",
            "McLaren",
            "McLaughlin Carriage Company",
            "MCV",
            "MDI",
            "Mecanique Aviation Traction",
            "Meeussen",
            "Mega",
            "Mekong Auto",
            "Melkus",
            "Mercedes-Benz",
            "Mercer",
            "Mercury",
            "Merkur",
            "Messerschmitt",
            "Metallurgique",
            "MG Motor",
            "Micro Cars",
            "Microcar",
            "Mills Extreme Vehicles (MEV)",
            "Minerva",
            "Minetti",
            "Mini",
            "Mitchell",
            "Mitsubishi",
            "Mitsuoka Motors",
            "MK Sportscars",
            "Mobius Motors",
            "Mohs",
            "Momo",
            "Monica",
            "Monteverdi",
            "Moose Jaw Standard",
            "Morattab",
            "Moretti",
            "Morgan Motor Company",
            "Morris Motors",
            "Moskvitch",
            "Mosler Automotive",
            "Move 101",
            "MTX aka Metalex",
            "Muntz",
            "Multicar",
            "MVS",
            "MZKT",
            "Car brands that start with N",
            "Car brands that start with N",
            "",
            "N H Buchanan Motor Co",
            "NAG",
            "Nagant & Cie, Liege",
            "NAM",
            "NAMCO",
            "Nardi",
            "Nash",
            "Nasr",
            "National",
            "Navistar",
            "NAZ",
            "Nazzaro",
            "Neoplan",
            "Neorion",
            "Netuar",
            "NEVS",
            "Nikola",
            "NIO",
            "Nissan",
            "Noble",
            "Norsk Automobil & Vagnfabrik AS",
            "Nota Sports and Racing",
            "NSU",
            "Nyayo",
            "Nysa",
            "Car brands that start with O",
            "Car brands that start with O",
            "",
            "Oakland",
            "Obvio",
            "ODA",
            "Ogle",
            "Ohta Jidosha",
            "Oka",
            "OKA Australia",
            "Oldsmobile",
            "OM",
            "Opel",
            "Opel India",
            "Orca Engineering",
            "Osca",
            "OSI",
            "Osterreichische Austro-Fiat",
            "Otomo",
            "Overland",
            "Car brands that start with P",
            "Car brands that start with P",
            "",
            "Paccar",
            "Packard",
            "Pagio",
            "Pagani",
            "Paige",
            "Pan-Car",
            "Panhard",
            "Panoz",
            "Panther",
            "Paramount",
            "Paterson",
            "Peel",
            "Peerless",
            "Pegaso",
            "Pender-Hertel",
            "Pennsylvania",
            "Perana Performance Group",
            "Perodua",
            "Perry",
            "Peterbilt Truck",
            "Peugeot",
            "PGO Automobiles",
            "Phantom Corsair",
            "Piaggio",
            "Picchio",
            "Pieper",
            "Pierce-Arrow",
            "Pinguin",
            "Pininfarina",
            "Piontek",
            "Pipe",
            "Pirin-Fiat",
            "Plymouth",
            "Polaris Industries",
            "Polarsun Automobile",
            "Polestar",
            "Pontiac",
            "Porsche",
            "PORTARO",
            "Praga",
            "PRB",
            "Premier Ltd",
            "Prince Motor Company",
            "Prodrive",
            "Proto Motors",
            "Proton",
            "Puch",
            "Puli",
            "Puma",
            "Purvis Eureka",
            "Pyeonghwa Motors",
            "Python",
            "Car brands that start with Q",
            "",
            "",
            "Qoros Auto Co",
            "Queen",
            "Qvale",
            "Car brands that start with R",
            "Car brands that start with R",
            "",
            "Radical",
            "Railton",
            "Ram",
            "Rambler",
            "Ranz",
            "Rapier",
            "Raymond Mays",
            "RCH",
            "Reliant",
            "Renault",
            "Revere",
            "Rezvani",
            "Rickenbacker",
            "Riga Autobus Factory",
            "Riley",
            "Rimac Automobili",
            "Rinspeed",
            "Rivian",
            "Roamer",
            "Rocar",
            "Rochdale",
            "Rochet-Schneider",
            "Roewe",
            "<liRonart",
            "",
            "Rolls-Royce",
            "Rootes Australia",
            "Rosenbauer",
            "Rossion Automotive",
            "Rover Company",
            "Ruf Automobile GmbH",
            "Rumpler",
            "Russell Motor",
            "Russo-Balt",
            "Ruston-Hornsby",
            "Car brands that start with S",
            "Car brands that start with S",
            "",
            "Saab",
            "SAIC Motor Corporation",
            "Sainte Claire",
            "SAIPA",
            "Saker",
            "Saleen",
            "Salmson",
            "San Storm",
            "Santa Matilde",
            "Saturn",
            "Saxon",
            "Sbarro",
            "Scania",
            "Scavas",
            "Scion",
            "Scott",
            "Scripps-Booth",
            "SEAT, S.A.",
            "Seoudi Group",
            "Setra",
            "SG Automotive Group",
            "Shaanxi Automobile Group",
            "Shamrock",
            "Shanghai Maple Guorun Automobile Co",
            "Sheffield-Simplex",
            "Shelby",
            "Shrike",
            "Shuanghuan Auto",
            "Siam Di Tella",
            "Siata",
            "Sichuan Tengzhong",
            "Simca",
            "Simca do Brasil",
            "Simca Vedette",
            "Singer",
            "Singulato",
            "Sinotruk (CNHTC)",
            "Sisu Auto",
            "Skoda Auto",
            "Smart",
            "SML Isuzu",
            "Sofia",
            "SOMACA",
            "Soueast",
            "Southern Cross",
            "Sovam",
            "SPA",
            "Spadaconcept",
            "Spania GTA",
            "Spectre",
            "Speranza Motors, Ltd",
            "Spetsteh",
            "Spirra",
            "Springuel",
            "Spyker N.V.",
            "Squire",
            "SRT",
            "SsangYong Motor Company",
            "SSC North America",
            "Sta Milde",
            "Standard",
            "Stanley",
            "Stearns Knight",
            "Stephens",
            "Sterling Trucks",
            "Steyr",
            "Stoewer",
            "Strathcarron",
            "Studebaker",
            "Studebaker of Canada Ltd",
            "Stutz",
            "Subaru",
            "Suffolk Sportscars",
            "Suminoe",
            "Sunbeam",
            "Superformance",
            "Suzuki Motor Corporation",
            "Swallow Doretti",
            "Syrena",
            "Car brands that start with T",
            "Car brands that start with T",
            "",
            "Talbot",
            "Tamplin",
            "Tara International",
            "Tarrant Automobile",
            "Tata Motor",
            "Tatra",
            "Tauro Sport Auto",
            "TAZ",
            "Tchaika",
            "TechArt",
            "Tecnologia Automotiva Catarinense",
            "Temperino",
            "Tesla Motors",
            "Schneider",
            "Thai Rung",
            "Thames",
            "The Knight XV",
            "The Roo Motor",
            "Theologou",
            "Think Global",
            "Timmis Motor Company",
            "TMC Costin",
            "Tofas",
            "Tommykaira",
            "Tornado",
            "Toyota",
            "Trabant",
            "Trackson",
            "Tracta",
            "Tramontana",
            "Trekka",
            "TREKOL",
            "Treser",
            "Trevethan",
            "Trident Cars Ltd",
            "Triking",
            "Trion",
            "Triumph Motor Company",
            "Trojan",
            "Troll",
            "Troller",
            "Tsukuba",
            "Tucker",
            "Turcat-Mery",
            "Turner",
            "Tushek & Spigel Supercars GmbH",
            "TVR",
            "Twombly",
            "Car brands that start with U",
            "Car brands that start with U",
            "",
            "UAZ",
            "Ultima Sports Ltd.",
            "UMM",
            "Unic",
            "Unicar",
            "Unipower",
            "Car brands that start with V",
            "Car brands that start with V",
            "",
            "Vaillante",
            "Vale",
            "Valmet Automotive",
            "VAM",
            "Van Hool NV",
            "Vanden Plas",
            "Vandenbrink",
            "Vauxhall",
            "Vauxhall Motors",
            "VDL Nedcar",
            "Vector Motors Corporation",
            "Vegantune",
            "Velie",
            "Vemac",
            "Vencer",
            "Venturi",
            "Venucia",
            "Vermorel",
            "Vernon-Derby",
            "Vespa",
            "Victoria",
            "Vignale",
            "Vinaxukior Xuan Kien",
            "Vinci",
            "Vivinus",
            "li>VLF",
            "",
            "Voisin",
            "Volga",
            "Volkswagen",
            "Volvo",
            " ",
            "",
            "Car brands that start with W",
            "Car brands that start with W",
            "",
            "W Motors",
            "Wallyscar",
            "Waltham",
            "Wanderer",
            "Warren-Lambert",
            "Warszawa",
            "Wartburg",
            "Warwick",
            "Weltmeister",
            "Wendax",
            "Western Star",
            "Westfield Sportscar",
            "WEY",
            "Wiesmann",
            "Wiima",
            "Wills",
            "Willys",
            "Willys-Overland",
            "Winnipeg",
            "Wolseley",
            "Woodill",
            "Workhorse",
            "Wuling",
            "Car brands that start with X",
            "Car brands that start with X",
            "",
            "Xinkai",
            "Xiali",
            "Xiamen Golden Dragon",
            "XPeng",
            "Car brands that start with Y",
            "Car brands that start with Y",
            "",
            "Yamaha",
            "Yes!",
            "Yo-Mobil",
            "Youngman",
            "Yue Lo0ng",
            "Yutong",
            "Car brands that start with ZCar brands that start with Z",
            "Zagato",
            "Zagross Khodro",
            "Zastava Special Vehicles",
            "ZAZor Zaporizhia Automobile Building Plant",
            "Zbrojovka Brno",
            "Zedel",
            "Zeekr",
            "Zender",
            "Zenos",
            "Zenvo",
            "Zeta",
            "Zhonghua",
            "Zhongtong",
            "ZiL",
            "Zimmer",
            "Zinoro",
            "ZIS",
            "Zotye Auto",
            "Zuk",
            "Zundapp",
            "Zust",
            "ZX Auto"});
            this.txtMake.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.txtMake.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txtMake.Location = new System.Drawing.Point(339, 504);
            this.txtMake.Name = "txtMake";
            this.txtMake.Size = new System.Drawing.Size(344, 44);
            this.txtMake.TabIndex = 13;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(807, 602);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(99, 37);
            this.label4.TabIndex = 14;
            this.label4.Text = "Color";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(104, 690);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(221, 37);
            this.label5.TabIndex = 15;
            this.label5.Text = "Transmission";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(807, 514);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(108, 37);
            this.label6.TabIndex = 16;
            this.label6.Text = "Model";
            // 
            // txtCarModel
            // 
            this.txtCarModel.AutoCompleteCustomSource.AddRange(new string[] {
            "4Runner",
            "Cordoba",
            "Gran Fury",
            "Nubira",
            "Sonic",
            "Acadia",
            "Corniche",
            "Gran Turismo",
            "Oasis",
            "Sonoma",
            "Accent",
            "Corolla",
            "Grand Am",
            "Odyssey",
            "Sorento",
            "Acclaim",
            "Coronet",
            "Grand Prix",
            "Omega",
            "Soul",
            "Accord",
            "Corrado",
            "Grand Vitara",
            "Omni",
            "Spark",
            "Achieva",
            "Corsair",
            "Grand Voyager",
            "Optima",
            "Spectra",
            "Aerio",
            "Corsica",
            "Greiz",
            "Outback",
            "Spectrum",
            "Aerostar",
            "Cortina",
            "Gremlin",
            "Outlander",
            "Spider",
            "Aileron",
            "Corvette",
            "Grenada",
            "Paceman",
            "Spirior",
            "Airstream",
            "Cougar",
            "Highlander",
            "Pacer",
            "Spirit",
            "Alero",
            "Countach",
            "Hobio",
            "Pacifica",
            "Sportage",
            "Allante",
            "Courier",
            "Hombre",
            "Pampa",
            "Sportvan",
            "Alliance",
            "Cressida",
            "Horizon",
            "Panamera",
            "Sprint",
            "Alpine",
            "Crider",
            "Hornet",
            "Parisienne",
            "Sprinter",
            "Altima",
            "Crossfire",
            "Hummer",
            "Park Avenue",
            "Spyder",
            "Amanti",
            "Crosstrek",
            "Hunter",
            "Park Ward",
            "Squire",
            "Amaze",
            "Crown Victoria",
            "Huracan",
            "Paseo",
            "St. Regis",
            "Amigo",
            "Cruze",
            "Husky",
            "Passat",
            "Stanza",
            "Anglia",
            "Cube",
            "Ikon",
            "Passport",
            "Starion",
            "Aperta",
            "Cutlass",
            "Impala",
            "Pathfinder",
            "Starlet",
            "Aries",
            "Dakota",
            "Imperial",
            "Patriot",
            "Starliner",
            "Armada",
            "Dart",
            "Impreza",
            "Phaeton",
            "Stealth",
            "Arnage",
            "Dasher",
            "Impulse",
            "Phantom",
            "Stelvio",
            "Arrow",
            "Daytona",
            "Inscription",
            "Phoenix",
            "Stinger",
            "Arya",
            "Defender",
            "Insight",
            "Pilot",
            "Storm",
            "Ascari",
            "del Sol",
            "Integra",
            "Pininfarina",
            "Strada",
            "Ascender",
            "Delta",
            "Intrepid",
            "Polara",
            "Stratus",
            "Ascent",
            "Demon",
            "Intrigue",
            "Popular",
            "Stylus",
            "Aspen",
            "DeVille",
            "Ioniq",
            "Portofino",
            "Suburban",
            "Aspire",
            "Diablo",
            "Jade",
            "Precis",
            "Summit",
            "Astra",
            "Diamante",
            "Javelin",
            "Prefect",
            "Sunbeam",
            "Astro",
            "Dino",
            "Jazz",
            "Prelude",
            "Sunbird",
            "Aura",
            "Diplomat",
            "Jetta",
            "Premier",
            "Sundance",
            "Aurora",
            "Discovery",
            "Jimmy",
            "Previa",
            "Sunfire",
            "Avalanche",
            "Drifter",
            "Juke",
            "Prius",
            "Sunliner",
            "Avalon",
            "Durango",
            "Justy",
            "Prizm",
            "Supra",
            "Avancier",
            "Duster",
            "Ka",
            "Probe",
            "Swift",
            "Avenger",
            "Dynasty",
            "Karma",
            "Pronto",
            "Tacoma",
            "Aventador",
            "Eagle",
            "Kingsway",
            "Protégé",
            "Tahoe",
            "Aveo",
            "Echo",
            "Kizashi",
            "Prowler",
            "Talon",
            "Aviator",
            "Eclipse",
            "Kodiak",
            "Pruis",
            "Taurus",
            "Axiom",
            "Econoline",
            "Kuga",
            "PT Cruiser",
            "Telstar",
            "Axxess",
            "Ecosport",
            "LaCrosse",
            "Pulsar",
            "Tempo",
            "Azera",
            "Edge",
            "Lagonda",
            "Puma",
            "Tercel",
            "Aztek",
            "Eight",
            "Lancer",
            "Quadrifoglio",
            "Terrain",
            "Azure",
            "Eighty-Eight",
            "Land Cruiser",
            "Quantum",
            "Terraza",
            "Baja",
            "Elan",
            "Landau",
            "Quattro",
            "Territory",
            "Barchetta",
            "Elantra",
            "Landaulet",
            "Quest",
            "Testarossa",
            "Beetle",
            "ElCamino",
            "Lanos",
            "Rabbit",
            "Thunderbird",
            "Bentayga",
            "Eldorado",
            "Laser",
            "Raider",
            "Tiburon",
            "Beretta",
            "Electra",
            "Laviolette",
            "Rainier",
            "Tiguan",
            "Berlinetta",
            "Element",
            "Leaf",
            "Rally",
            "Titan",
            "Blackwood",
            "Elise",
            "LeBaron",
            "Ram",
            "Topaz",
            "Blazer",
            "Elite",
            "Legacy",
            "Ramcharger",
            "Torino",
            "Bonneville",
            "Elysion",
            "Leganza",
            "Rampage",
            "Toronado",
            "Borrego",
            "Enclave",
            "Legend",
            "Ranchero",
            "Torrent",
            "Boxter",
            "Encore",
            "LeMans",
            "Range Rover",
            "Touareg",
            "Brat",
            "Entourage",
            "LeSabre",
            "Ranger",
            "Touring",
            "Brava",
            "Envision",
            "Levante",
            "Rapide",
            "Town & Country",
            "Bravada",
            "Envoy",
            "Liberte",
            "Reatta",
            "Town Car",
            "Breeze",
            "Enzo",
            "Liberty",
            "Rebel",
            "Tracer",
            "Brio",
            "Eos",
            "Loyale",
            "Regal",
            "tracker",
            "Bronco",
            "Equator",
            "Lucerne",
            "Regency",
            "TrailBlazer",
            "Brooklands",
            "Equinox",
            "Lumina",
            "Regent",
            "Trans Sport",
            "Brougham",
            "Equus",
            "Luv",
            "Reliant",
            "Traverse",
            "Caballero",
            "Escalade",
            "Lynx",
            "Rendezvous",
            "Trax",
            "Cabrio",
            "Escape",
            "Macan",
            "Renegade",
            "Tredia",
            "Cabriolet",
            "Escort",
            "Magnum",
            "Reno",
            "Tribeca",
            "Cadenza",
            "Esperante",
            "Malibu",
            "Ridgeline",
            "Tribute",
            "Calais",
            "Esprit",
            "Mangusta",
            "Rio",
            "Trooper",
            "Caliber",
            "Estate",
            "Maranello",
            "Riviera",
            "Tuareg",
            "California",
            "Esteem",
            "Marauder",
            "Roadmaster",
            "Tucson",
            "Camargue",
            "Eurovan",
            "Mariner",
            "Roadster",
            "Tundra",
            "Camry",
            "Evora",
            "Marquis",
            "Rocky",
            "Turbo",
            "Canyon",
            "Excel",
            "Matador",
            "Rodeo",
            "Turismo",
            "Capri",
            "Excursion",
            "Matrix",
            "Rogue",
            "Uplander",
            "Caprice",
            "Executive",
            "Maverick",
            "Rondo",
            "Valiant",
            "Caravan",
            "Exige",
            "Maxima",
            "Routan",
            "Vamos",
            "Caravelle",
            "Expedition",
            "Maybach",
            "Royal",
            "Vanagon",
            "Carrera",
            "Explorer",
            "Mayfair",
            "Royale",
            "Vanden",
            "Cascada",
            "Expo",
            "Meadowbrook",
            "Sable",
            "Vandura",
            "Catera",
            "Express",
            "Medallion",
            "Safari",
            "Vanquish",
            "Cavalier",
            "Fairlaine",
            "Meteor",
            "Samurai",
            "Vantage",
            "Cayenne",
            "Fairmont",
            "Metro",
            "Samuri",
            "VehiCROSS",
            "Cayman",
            "Falcon",
            "Miata",
            "Santa Fe",
            "Veloster",
            "Celebrity",
            "Festiva",
            "Midget",
            "Sapporo",
            "Venture",
            "Celica",
            "Fiero",
            "Milan",
            "Saratoga",
            "Venza",
            "Centura",
            "Fiesta",
            "Milano",
            "Savana",
            "Veracruz",
            "Century",
            "Fifth Avenue",
            "Millenia",
            "Scaglietti",
            "Verano",
            "Challenger",
            "Figo",
            "Mirada",
            "Scamp",
            "Verona",
            "Champ",
            "Firebird",
            "Mirage",
            "Scirocco",
            "Versa",
            "Charade",
            "Firenza",
            "Mirai",
            "Scorpio",
            "Veyron",
            "Charger",
            "Fit",
            "Mobilio",
            "Scrambler",
            "Vezel",
            "Cherokee",
            "Fleetwood",
            "Modena",
            "Sebring",
            "Vibe",
            "Chevelle",
            "Flex",
            "Modulo",
            "Sedona",
            "Vigor",
            "Chevette",
            "Flying Spur",
            "Monaco",
            "Senior",
            "Villager",
            "Cheyenne",
            "Focus",
            "Mondeo",
            "Sentra",
            "Viper",
            "Ciera",
            "Forenza",
            "Mondial",
            "Sephia",
            "Virage",
            "Cimarron",
            "Forester",
            "Montana",
            "Sequoia",
            "Viscount",
            "Cirrus",
            "Forte",
            "Monte Carlo",
            "Seville",
            "Vision",
            "Citation",
            "Fox",
            "Montego",
            "Shadow",
            "Vitara",
            "City",
            "Freed",
            "Monterey",
            "Sidekick",
            "Vogue",
            "Civic",
            "Freed Spike",
            "Montero",
            "Sienna",
            "Volt",
            "Club Wagon",
            "Freelander",
            "Mountaineer",
            "Sierra",
            "Voyager",
            "Clubman",
            "Frontier",
            "Mulsanne",
            "Sigma",
            "Vue",
            "Cobalt",
            "Fuego",
            "Murano",
            "Silhouette",
            "Wagoneer",
            "Colorado",
            "Fusion",
            "Murcielago",
            "Silver Dawn",
            "Wayfarer",
            "Colt",
            "Galant",
            "Mustang",
            "Silver Seraph",
            "Windsor",
            "Comanche",
            "Galaxie",
            "Mystique",
            "Silver Shadow",
            "Windstar",
            "Compass",
            "Galaxy",
            "Mythos",
            "Silver Spirit",
            "Wraith",
            "Concord",
            "Gallardo",
            "Navajo",
            "Silver Spur",
            "Wrangler",
            "Concorde",
            "Genesis",
            "Navigator",
            "Silver Wraith",
            "Xterra",
            "Conquest",
            "Ghibli",
            "Neon",
            "Silverado",
            "Yaris",
            "Consul",
            "Gienia",
            "New Yorker",
            "Skyhawk",
            "Ypsilon",
            "Continental",
            "Giulia",
            "Newport",
            "Skylark",
            "Yukon",
            "Contour",
            "Golf",
            "Ninety-Eight",
            "Solara",
            "Zephyr",
            "Cooper",
            "Grace",
            "Niro",
            "Somerset",
            "Cordia",
            "Graduate",
            "Nova",
            "Sonata"});
            this.txtCarModel.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;
            this.txtCarModel.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.CustomSource;
            this.txtCarModel.Location = new System.Drawing.Point(1037, 504);
            this.txtCarModel.Name = "txtCarModel";
            this.txtCarModel.Size = new System.Drawing.Size(344, 44);
            this.txtCarModel.TabIndex = 17;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(104, 602);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(89, 37);
            this.label7.TabIndex = 18;
            this.label7.Text = "Year";
            // 
            // txtVin
            // 
            this.txtVin.Location = new System.Drawing.Point(1037, 690);
            this.txtVin.MaxLength = 10;
            this.txtVin.Name = "txtVin";
            this.txtVin.Size = new System.Drawing.Size(344, 44);
            this.txtVin.TabIndex = 23;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label8.Location = new System.Drawing.Point(807, 693);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(198, 37);
            this.label8.TabIndex = 22;
            this.label8.Text = "Vin Number";
            // 
            // cbYear
            // 
            this.cbYear.FormattingEnabled = true;
            this.cbYear.Items.AddRange(new object[] {
            "2015",
            "2016",
            "2017",
            "2018",
            "2019",
            "2020",
            "2021",
            "2022",
            "2023"});
            this.cbYear.Location = new System.Drawing.Point(339, 598);
            this.cbYear.Name = "cbYear";
            this.cbYear.Size = new System.Drawing.Size(344, 45);
            this.cbYear.TabIndex = 24;
            // 
            // cbColor
            // 
            this.cbColor.FormattingEnabled = true;
            this.cbColor.Items.AddRange(new object[] {
            "White",
            "Silver",
            "Black",
            "Dark Gray",
            "Red",
            "Blue",
            "Brown",
            "Green",
            "Yellow"});
            this.cbColor.Location = new System.Drawing.Point(1037, 602);
            this.cbColor.Name = "cbColor";
            this.cbColor.Size = new System.Drawing.Size(344, 45);
            this.cbColor.TabIndex = 25;
            // 
            // cbTransmission
            // 
            this.cbTransmission.FormattingEnabled = true;
            this.cbTransmission.Items.AddRange(new object[] {
            "Manual",
            "AMT ",
            "CVT",
            "Automatic"});
            this.cbTransmission.Location = new System.Drawing.Point(339, 690);
            this.cbTransmission.Name = "cbTransmission";
            this.cbTransmission.Size = new System.Drawing.Size(344, 45);
            this.cbTransmission.TabIndex = 26;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.ForeColor = System.Drawing.Color.White;
            this.label9.Location = new System.Drawing.Point(1450, 989);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(102, 37);
            this.label9.TabIndex = 27;
            this.label9.Text = "label9";
            // 
            // frm_Add_Car
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(19F, 37F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1564, 1035);
            this.Controls.Add(this.label9);
            this.Controls.Add(this.cbTransmission);
            this.Controls.Add(this.cbColor);
            this.Controls.Add(this.cbYear);
            this.Controls.Add(this.txtVin);
            this.Controls.Add(this.label8);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.txtCarModel);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txtMake);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.btnClear);
            this.Controls.Add(this.btnSaveCar);
            this.Controls.Add(this.btnBackToMenu);
            this.Controls.Add(this.pictureBox1);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frm_Add_Car";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Add Car";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button btnClear;
        private System.Windows.Forms.Button btnSaveCar;
        private System.Windows.Forms.Button btnBackToMenu;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox txtMake;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox txtCarModel;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox txtVin;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.ComboBox cbYear;
        private System.Windows.Forms.ComboBox cbColor;
        private System.Windows.Forms.ComboBox cbTransmission;
        private System.Windows.Forms.Label label9;
    }
}